version:  "3"

services:
  broker1:
    image:  csp-base-stdio:latest
    stdin_open: true
    tty:  true
    command: /libcsp/build/examples/zmqproxy -v 1
    logging:
      driver: syslog
      options:
        syslog-address: udp:syslog-ng:514
        max-size: "10m"
    ports:
      - 6000
    networks:
      - udp1
  server1:
    image:  csp-base-stdio:latest
    stdin_open: true
    tty:  true
    command: /libcsp/build/examples/csp_server_client -a 1 -z broker1
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: "10m"
    networks:
      - udp1
  client1:
    image: csp-base-stdio:latest
    stdin_open: true
    tty:  true
    command: tail -f /dev/null
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: "10m"
    networks:
      - udp1
  bridge1:
    image:  csp-base-stdio:latest
    stdin_open: true
    tty:  true
    command: /libcsp/build/examples/csp_bridge -h udpt1 -m 1 -r 1 -d -d -d -d
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 9600:9600/udp
    networks:
      - udp1
      - udp2
  broker2:
    image:  csp-base-stdio:latest
    stdin_open: true
    tty:  true
    command: /libcsp/build/examples/zmqproxy -v 1
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 6000
    networks:
      - udp2
  server2:
    image:  csp-base-stdio:latest
    stdin_open: true
    tty:  true
    command: /libcsp/build/examples/csp_server_client -a 10 -z broker2 -q
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: "10m"
    networks:
      - udp2
  client2:
    image: csp-base-stdio:latest
    stdin_open: true
    tty:  true
    command: tail -f /dev/null
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: "10m"
    networks:
      - udp2
  bridge2:
    image:  csp-base-stdio:latest
    stdin_open: true
    tty:  true
    command: /libcsp/build/examples/csp_bridge -h udpt2 -m 1 -r 1 -d -d -d -d
    logging:
      driver: local
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - 9700:9700/udp
    networks:
      - udp1
      - udp2
  syslog-ng:
    image: lscr.io/linuxserver/syslog-ng
    container_name: syslog-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=GMT
    volumes:
      - /path/to/config:syslog-ng/config
      - /path/to/log:syslog-ng/logs
    ports:
      - 514:5514/udp
      - 601:6601/tcp
      - 6514:6514/tcp
    restart: unless-stopped
    networks:
      - udp1
      - udp2
networks:
  udp1:
  udp2:

