version:  "3"

services:
  broker1:
    image:  csp-base-stdio:latest
    command: /libcsp/build/examples/zmqproxy -v 1
    ports:
      - 6000
    networks:
      - udp1
  server1:
    image:  csp-base-stdio:latest
    command: /libcsp/build/examples/csp_server_client -a 1 -z broker1
    networks:
      - udp1
  client1:
    image: csp-base-stdio:latest
    command: tail /dev/null
    networks:
      - udp1
  bridge1:
    image:  csp-base-stdio:latest
    command: /libcsp/build/examples/csp_bridge -h udpt1 -m 1 -r 1 -d -d -d -d
    ports:
      - 9600:9600/udp
    networks:
      - udp1
networks:
  udp1:

