# Dockerfile for libcsp and friends
FROM csp-base-stdio as builder-image

FROM ubuntu:20.04 AS runner-image
RUN apt-get update && apt-get install --no-install-recommends -y libczmq4 mosquitto mosquitto-dev mosquitto-clients libmosquitto-dev && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd --create-home csp
COPY --from=builder-image libcsp/build/examples /home/csp/bin

USER csp

EXPOSE 6000/tcp
EXPOSE 7000/tcp
EXPOSE 6001/udp
EXPOSE 6002/udp

CMD ["/home/csp/bin/csp_bridge"]