# Dockerfile for libcsp and friends
FROM csp-base-stdio as builder-image

FROM ubuntu:20.04 AS runner-image
RUN apt-get update && apt-get install --no-install-recommends -y libczmq4 && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd --create-home csp
COPY --from=builder-image libcsp/build/examples /home/csp/apps

USER csp

EXPOSE 6000/tcp
EXPOSE 7000/tcp

CMD ["/home/csp/bin/zmqproxy"]
